### ISSUE TITLE
 visit info page must be displayed automatically"

### ISSUE THREAD

**Issue by Aryasatheesan** [vasudevareddyreddem/hospital#12]
![image](https://user-images.githubusercontent.com/39790889/41271312-85d9a656-6e2d-11e8-887a-3ce6a47dab49.png)

receptionist	"front desk-->ip new registration"	billing"on clickingbilling tab visit info page must be displayed automatically"
ehealthi: nfra.com/resources/desk
Browserchrome

not  a bug

**Comment by bayapucg** [comment]
not a bug
