### ISSUE TITLE
screen resolution 800*600

### ISSUE THREAD

**Issue by Aryasatheesan** [vasudevareddyreddem/hospital#15]
![image](https://user-images.githubusercontent.com/39790889/41271491-99b2be0a-6e2e-11e8-9dcb-9a64d0565457.png)
screen resolution 800*600
browser: Chrome
ehealthinfra.com/hospital

role:admin

responsive wroking fine

**Comment by bayapucg** [comment]
responsive wroking fine

**Comment by bayapucg** [comment]
responsive wroking fine
