### ISSUE TITLE
chat and hospital both are highlighting at a time.

### ISSUE THREAD

**Issue by Aryasatheesan** [vasudevareddyreddem/hospital#17]
![image](https://user-images.githubusercontent.com/39790889/41271615-38bc8df0-6e2f-11e8-827c-4a581b5a773b.png)

chat and hospital both are highlighting at a time.
browser-chrome
http://ehealthinfra.com/dashboard

funtioanlity

**Comment by bayapucg** [comment]
funtioanlity
