### ISSUE TITLE
 Graph is not displaying in mobile.

### ISSUE THREAD

**Issue by Aryasatheesan** [vasudevareddyreddem/hospital#18]
![image](https://user-images.githubusercontent.com/39790889/41272651-9d61057a-6e33-11e8-8eeb-e1db0b9645b5.png)
 Graph is not displaying in mobile.
browers-chrome,mozilla,opera,uc browser
http://ehealthinfra.com/dashboard

**Comment by bayapucg** [comment]
as for discussion Graphs hide in mobiles
