### ISSUE TITLE
Not displaying all the fields but when screen is rotated fields are displayed.

### ISSUE THREAD

**Issue by Aryasatheesan** [vasudevareddyreddem/hospital#19]
![image](https://user-images.githubusercontent.com/39790889/41273057-796ccdf0-6e35-11e8-99a4-327261186739.png)

Not displaying all the fields but when screen is rotated fields are displayed.
mobile-->chrome browser
role-->admin
http://ehealthinfra.com/hospital/add/MQ==

**Comment by bayapucg** [comment]
complete

**Comment by Aryasatheesan** [comment]
done
