### ISSUE TITLE
on clicking add hospital, the details are shown at the bottom.

### ISSUE THREAD

**Issue by Aryasatheesan** [vasudevareddyreddem/hospital#20]
![image](https://user-images.githubusercontent.com/39790889/41273240-5541d942-6e36-11e8-8f19-cb50b3a843df.png)
on clicking add hospital, the details are shown at the bottom. It must be displayed in new page.
http://ehealthinfra.com/hospital/add/MQ==
Mobile-->chrome browser

**Comment by bayapucg** [comment]
complete
