### ISSUE TITLE
Improper alignment

### ISSUE THREAD

**Issue by Aryasatheesan** [vasudevareddyreddem/hospital#21]
![image](https://user-images.githubusercontent.com/39790889/41273366-cbeab17c-6e36-11e8-84d9-f5b1d905b834.png)

![image](https://user-images.githubusercontent.com/39790889/41273470-42da2a6a-6e37-11e8-9753-5601c5c49fcf.png)

Improper alignment
mobile-->chrome
role-admin
http://ehealthinfra.com/admin/announcement

**Comment by bayapucg** [comment]
complete

**Comment by Aryasatheesan** [comment]
reopen

**Comment by bayapucg** [comment]
complete
