### ISSUE TITLE
Graph is not displayed in hospital admin

### ISSUE THREAD

**Issue by Aryasatheesan** [vasudevareddyreddem/hospital#22]
![image](https://user-images.githubusercontent.com/39790889/41273673-088a0f00-6e38-11e8-9ebe-5b9df63ad291.png)

Graph is not displayed in hospital admin
http://ehealthinfra.com/dashboard
role-hospital admin
mobile-->chrome

**Comment by bayapucg** [comment]
graph hides in mobile
