### ISSUE TITLE
Entire data not displayed

### ISSUE THREAD

**Issue by Aryasatheesan** [vasudevareddyreddem/hospital#27]
![image](https://user-images.githubusercontent.com/39790889/41274848-82a92218-6e3c-11e8-836b-fe3ff7598232.png)

Entire data not displayed
http://ehealthinfra.com/lab/outsources_labtests
role-lab coordinator
mobile-->chrome

**Comment by bayapucg** [comment]
complete

**Comment by Aryasatheesan** [comment]
reopen
