### ISSUE TITLE
Add treatment button aligned improper in mozilla

### ISSUE THREAD

**Issue by Aryasatheesan** [vasudevareddyreddem/hospital#31]
![image](https://user-images.githubusercontent.com/39790889/41342582-39ca1d20-6f1a-11e8-9273-290e913be2a9.png)

Add treatment button aligned improper in mozilla
http://ehealthinfra.com/hospital/addtreatment
role-->hospital admin
browser-mozilla

**Comment by bayapucg** [comment]
complete

**Comment by Aryasatheesan** [comment]
not resolved
